# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-24 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Transaction')),
                ('approval_comment', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.User')),
                ('originator_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='originator_charge', to='core.Charge')),
                ('participating_accounts', models.ManyToManyField(to='core.Account')),
                ('shares', models.ManyToManyField(blank=True, related_name='shares', to='core.Charge')),
            ],
            bases=('core.transaction',),
        ),
        migrations.RemoveField(
            model_name='costsharing',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='costsharing',
            name='participating_accounts',
        ),
        migrations.RemoveField(
            model_name='costsharing',
            name='transaction_ptr',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='participating_accounts',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='transaction_ptr',
        ),
        migrations.RemoveField(
            model_name='proceedssharing',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='proceedssharing',
            name='participating_accounts',
        ),
        migrations.RemoveField(
            model_name='proceedssharing',
            name='transaction_ptr',
        ),
        migrations.RemoveField(
            model_name='recovery',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='recovery',
            name='participating_accounts',
        ),
        migrations.RemoveField(
            model_name='recovery',
            name='transaction_ptr',
        ),
        migrations.DeleteModel(
            name='CostSharing',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='ProceedsSharing',
        ),
        migrations.DeleteModel(
            name='Recovery',
        ),
    ]
