# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PayOutcredit',
            new_name='PayOutbalance',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='credit',
            new_name='balance',
        ),
    ]
