# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170114_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='contents',
            field=models.CharField(default='', max_length=100),
        ),
    ]
