# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161109_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='batch',
        ),
        migrations.AddField(
            model_name='taking',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Batch'),
            preserve_default=False,
        ),
    ]
