# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161021_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='users',
            field=models.ManyToManyField(blank=True, to='core.User'),
        ),
    ]
