# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-26 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170426_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Transaction')),
                ('approval_comment', models.TextField(blank=True)),
            ],
            bases=('core.transaction',),
        ),
        migrations.CreateModel(
            name='CostSharing',
            fields=[
                ('sharetransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ShareTransaction')),
            ],
            bases=('core.sharetransaction',),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('sharetransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ShareTransaction')),
            ],
            bases=('core.sharetransaction',),
        ),
        migrations.CreateModel(
            name='ProceedsSharing',
            fields=[
                ('sharetransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ShareTransaction')),
            ],
            bases=('core.sharetransaction',),
        ),
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('sharetransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ShareTransaction')),
            ],
            bases=('core.sharetransaction',),
        ),
        migrations.AddField(
            model_name='sharetransaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AddField(
            model_name='sharetransaction',
            name='originator_share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='originator_share', to='core.Charge'),
        ),
        migrations.AddField(
            model_name='sharetransaction',
            name='participating_accounts',
            field=models.ManyToManyField(to='core.Account'),
        ),
        migrations.AddField(
            model_name='sharetransaction',
            name='shares',
            field=models.ManyToManyField(blank=True, related_name='shares', to='core.Charge'),
        ),
    ]
