# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161109_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='restitution',
            name='batch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Batch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='original_taking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Taking'),
        ),
    ]
