# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161021_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='average_consumption',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='batch',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='consumable',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Consumable'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='date_of_expiry',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='parcel_approx',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='batch',
            name='production_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='purchase_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='special_density',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='batch',
            name='stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Supplier'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='taken',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='batch',
            name='unit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Unit'),
        ),
    ]
