# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_unit_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='contents',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='unit',
            name='plural',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
