# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-26 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170224_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaloffer',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='generaloffer',
            name='distance_add',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generaloffer',
            name='distance_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generaloffer',
            name='grower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grower', to='core.Supplier'),
        ),
        migrations.AlterField(
            model_name='generaloffer',
            name='orderpos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generaloffer',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processor', to='core.Supplier'),
        ),
        migrations.AlterField(
            model_name='generaloffer',
            name='supply_stock',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generaloffer',
            name='variety',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
