# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170118_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositation',
            old_name='moneybox',
            new_name='money_box',
        ),
        migrations.RenameField(
            model_name='inpayment',
            old_name='moneybox',
            new_name='money_box',
        ),
        migrations.RenameField(
            model_name='moneyboxstock',
            old_name='moneybox',
            new_name='money_box',
        ),
        migrations.RenameField(
            model_name='payoutbalance',
            old_name='moneybox',
            new_name='money_box',
        ),
        migrations.RenameField(
            model_name='payoutdeposit',
            old_name='moneybox',
            new_name='money_box',
        ),
    ]
