# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-27 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170426_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accpayphase',
            name='account',
        ),
        migrations.AlterField(
            model_name='product',
            name='storability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
