# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-26 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170226_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='available_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='official',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='orderpos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='supply_stock',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
