# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-27 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170427_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='accpayphase',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Account'),
        ),
    ]
