# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-26 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170119_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_entry_type', models.BooleanField()),
                ('to_balance', models.BooleanField()),
            ],
        ),
    ]
