# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
