# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_consumptionestimation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='positive',
            field=models.BooleanField(default=True),
        ),
    ]
