# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transaction_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restitution',
            name='approval_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='positive',
            field=models.BooleanField(),
        ),
    ]
