# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-26 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170226_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='basic_price',
        ),
    ]
