# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161116_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='positive',
        ),
        migrations.AddField(
            model_name='transaction',
            name='sign',
            field=models.IntegerField(default=0),
        ),
    ]
