# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161021_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='consumable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Consumable'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Supplier'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Unit'),
        ),
    ]
