# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-26 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='no',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
