# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161116_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='sign',
        ),
        migrations.AddField(
            model_name='transaction',
            name='positive',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
