# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20161021_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='comment',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='description',
            field=models.TextField(blank=True, default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
