# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-06 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170506_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='official',
        ),
        migrations.AlterField(
            model_name='offer',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
