# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20161116_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpayment',
            name='confirmation_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inpayment',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Currency'),
        ),
    ]
