# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161022_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualuser',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='taken',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='address_notice',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='streetname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='streetnumber',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='telephone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='town',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='website',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='accounts',
            field=models.ManyToManyField(blank=True, to='core.Account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='virtualuser',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
