# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161116_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='positive',
            field=models.NullBooleanField(),
        ),
    ]
