# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-07 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170507_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='packing',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
