# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20161117_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='to_balance',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='positive',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
