# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20161022_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='is_containerer',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='is_devicer',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='is_packager',
        ),
        migrations.AddField(
            model_name='supplier',
            name='broad_location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_container_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_device_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_packaging_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accpayphases',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='batchstorage',
            name='amount_approx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchstorage',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='batchstorage',
            name='is_reserve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storagecondition',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='address_notice',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='streetname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='streetnumber',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='town',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address_notice',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='animals',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='basic_cost',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=3, default=None, default_currency='EUR', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='delivery_cost_gen',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=3, default=None, default_currency='EUR', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='delivery_cost_per_unit',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=3, default=None, default_currency='EUR', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='distribution',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='focus',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='full_names',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_grower',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_processor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_retailer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_wholesale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='max_order_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='min_interval',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='min_order_value',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=3, default=None, default_currency='EUR', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='min_order_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='official',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='processing',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='streetname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='streetnumber',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='structure',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='telephone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='town',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='unit_for_delivery_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
