# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20161117_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositation',
            name='confirmation_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='moneyboxstock',
            name='stock',
            field=models.FloatField(default=0),
        ),
    ]
