# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-07 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_offer_packing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='quantity',
            new_name='parcels_included',
        ),
        migrations.AddField(
            model_name='offer',
            name='continuous',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='minimum_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offer',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='parcel',
            field=models.FloatField(default=1),
        ),
    ]
