# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-07 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170507_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_persons',
            field=models.ManyToManyField(blank=True, null=True, to='core.Person'),
        ),
    ]
