# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20161117_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='positive',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_balance',
            field=models.NullBooleanField(),
        ),
    ]
