# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20161117_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Batch'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Currency'),
        ),
    ]
