# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-08 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170507_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_persons',
            field=models.ManyToManyField(blank=True, to='core.Person'),
        ),
    ]
