# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 15:47
from __future__ import unicode_literals

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20161025_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=3, default=None, default_currency='EUR', max_digits=8, null=True),
        ),
    ]
