# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 15:47
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20161025_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=djmoney.models.fields.MoneyField(decimal_places=3, default=Decimal('0'), default_currency='EUR', max_digits=8),
        ),
    ]
