# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-08 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170508_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaloffer',
            name='original_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generaloffer',
            name='original_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='original_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='original_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
