# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20161025_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='value',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='value_currency',
        ),
    ]
