# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-08 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170508_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='original_id',
            new_name='original_no',
        ),
        migrations.AddField(
            model_name='batch',
            name='no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
