# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-28 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20161128_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accpayphase',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
