# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-28 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20161128_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accpayphase',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accpayphase',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
