# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-28 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20161128_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accpayphase',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='accpayphase',
            old_name='start_date',
            new_name='start',
        ),
    ]
