# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20161025_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='credit_currency',
        ),
        migrations.RemoveField(
            model_name='account',
            name='deposit_currency',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='presumed_price_currency',
        ),
        migrations.RemoveField(
            model_name='insertion',
            name='balance_currency',
        ),
        migrations.RemoveField(
            model_name='insertion',
            name='basic_cost_currency',
        ),
        migrations.RemoveField(
            model_name='insertion',
            name='delivery_cost_currency',
        ),
        migrations.RemoveField(
            model_name='insertion',
            name='discount_currency',
        ),
        migrations.RemoveField(
            model_name='insertion',
            name='sum_of_lot_prices_currency',
        ),
        migrations.RemoveField(
            model_name='insertion',
            name='total_cost_currency',
        ),
        migrations.RemoveField(
            model_name='insertion',
            name='total_price_currency',
        ),
        migrations.RemoveField(
            model_name='instalment',
            name='amount_currency',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='basic_price_currency',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount_currency',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='total_price_currency',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='basic_cost_currency',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='delivery_cost_gen_currency',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='delivery_cost_per_unit_currency',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='min_order_value_currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='value_currency',
        ),
        migrations.AlterField(
            model_name='account',
            name='credit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='deposit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='batch',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='presumed_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='basic_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='delivery_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='sum_of_lot_prices',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='total_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instalment',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='basic_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='basic_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='delivery_cost_gen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='delivery_cost_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='min_order_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
