# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20161025_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='account',
            name='deposit',
        ),
    ]
