# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-26 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_credittodeposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiontype',
            name='to_balance',
        ),
    ]
