# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-28 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20161128_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accpayphase',
            name='account',
        ),
        migrations.AddField(
            model_name='accpayphase',
            name='account',
            field=models.ManyToManyField(to='core.Account'),
        ),
    ]
