# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-03 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20161128_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('to_balance', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
            ],
        ),
        migrations.RenameField(
            model_name='costsharing',
            old_name='excepted_accounts',
            new_name='participating_accounts',
        ),
        migrations.RenameField(
            model_name='insertion',
            old_name='by_user',
            new_name='entered_by_user',
        ),
        migrations.RenameField(
            model_name='insertion',
            old_name='by_user_comment',
            new_name='user_comment',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='by_user',
            new_name='entered_by_user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='charged_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='positive',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_balance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='value',
        ),
        migrations.AddField(
            model_name='transaction',
            name='involved_accounts',
            field=models.ManyToManyField(related_name='involved_accounts', to='core.Account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='originator_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='originator_account', to='core.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Transaction'),
        ),
    ]
