# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20161028_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='deposit',
            field=models.FloatField(default=0),
        ),
    ]
