# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20161028_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='account',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='price',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='presumed_price',
        ),
        migrations.RemoveField(
            model_name='insertion',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='insertion',
            name='basic_cost',
        ),
        migrations.RemoveField(
            model_name='insertion',
            name='delivery_cost',
        ),
        migrations.RemoveField(
            model_name='insertion',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='insertion',
            name='sum_of_lot_prices',
        ),
        migrations.RemoveField(
            model_name='insertion',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='insertion',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='instalment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='basic_price',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='basic_cost',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='delivery_cost_gen',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='delivery_cost_per_unit',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='min_order_value',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='value',
        ),
    ]
