# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-08 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20170726_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insertion',
            name='specific_insertions',
        ),
        migrations.RemoveField(
            model_name='specificinsertion',
            name='supplier',
        ),
        migrations.AddField(
            model_name='credit',
            name='insertion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Insertion'),
        ),
        migrations.AddField(
            model_name='insertion',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='insertion',
            name='name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='specificinsertion',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specificinsertion',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Batch'),
        ),
        migrations.AddField(
            model_name='specificinsertion',
            name='insertion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Insertion'),
        ),
    ]
