# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20161028_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='deposit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumable',
            name='presumed_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insertion',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insertion',
            name='basic_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insertion',
            name='delivery_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insertion',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insertion',
            name='sum_of_lot_prices',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insertion',
            name='total_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insertion',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instalment',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='basic_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='basic_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='delivery_cost_gen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='delivery_cost_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='min_order_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
