# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-04 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_charge_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='excepted_accounts',
            new_name='participating_accounts',
        ),
        migrations.RenameField(
            model_name='proceedssharing',
            old_name='excepted_accounts',
            new_name='participating_accounts',
        ),
        migrations.RenameField(
            model_name='recovery',
            old_name='excepted_accounts',
            new_name='participating_accounts',
        ),
        migrations.AlterField(
            model_name='costsharing',
            name='approval_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='approval_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proceedssharing',
            name='approval_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='approval_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='involved_accounts',
            field=models.ManyToManyField(blank=True, null=True, related_name='involved_accounts', to='core.Account'),
        ),
    ]
