# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-08 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20170808_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificinsertion',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Batch'),
        ),
        migrations.AlterField(
            model_name='specificinsertion',
            name='insertion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Insertion'),
        ),
    ]
