# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-06 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20170104_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
