# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20161028_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSharing',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Transaction')),
                ('approval_comment', models.TextField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
            bases=('core.transaction',),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('conversion_rate', models.FloatField(default=1)),
                ('full_name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depositation',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Transaction')),
                ('confirmation_comment', models.TextField()),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.User')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Currency')),
            ],
            bases=('core.transaction',),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Transaction')),
                ('approval_comment', models.TextField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
            bases=('core.transaction',),
        ),
        migrations.CreateModel(
            name='Inpayment',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Transaction')),
                ('confirmation_comment', models.TextField()),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.User')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Currency')),
            ],
            bases=('core.transaction',),
        ),
        migrations.CreateModel(
            name='MoneyBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stock_value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyBoxStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Currency')),
                ('moneybox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MoneyBox')),
            ],
        ),
        migrations.CreateModel(
            name='PayOutBalance',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Transaction')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Currency')),
                ('moneybox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MoneyBox')),
            ],
            bases=('core.transaction',),
        ),
        migrations.CreateModel(
            name='PayOutDeposit',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Transaction')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Currency')),
                ('moneybox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MoneyBox')),
            ],
            bases=('core.transaction',),
        ),
        migrations.CreateModel(
            name='ProceedsSharing',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Transaction')),
                ('approval_comment', models.TextField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
            bases=('core.transaction',),
        ),
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Transaction')),
                ('approval_comment', models.TextField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
            bases=('core.transaction',),
        ),
        migrations.CreateModel(
            name='Restitution',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Transaction')),
                ('approval_comment', models.TextField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
            bases=('core.transaction',),
        ),
        migrations.RenameModel(
            old_name='TakingGood',
            new_name='Taking',
        ),
        migrations.RenameModel(
            old_name='TrTransfer',
            new_name='Transfer',
        ),
        migrations.RemoveField(
            model_name='trcommon',
            name='excepted_accounts',
        ),
        migrations.RemoveField(
            model_name='trcommon',
            name='transaction_ptr',
        ),
        migrations.RemoveField(
            model_name='trcredit_in_good',
            name='insertion',
        ),
        migrations.RemoveField(
            model_name='trcredit_in_good',
            name='transaction_ptr',
        ),
        migrations.RemoveField(
            model_name='trcredit_in_money',
            name='transaction_ptr',
        ),
        migrations.RemoveField(
            model_name='trcredit_out_money',
            name='transaction_ptr',
        ),
        migrations.RemoveField(
            model_name='trdeposit_in',
            name='transaction_ptr',
        ),
        migrations.RemoveField(
            model_name='trdeposit_out',
            name='transaction_ptr',
        ),
        migrations.RemoveField(
            model_name='trdistribution',
            name='excepted_accounts',
        ),
        migrations.RemoveField(
            model_name='trdistribution',
            name='transaction_ptr',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='credit',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='insertion',
            old_name='balance',
            new_name='difference',
        ),
        migrations.DeleteModel(
            name='TrCommon',
        ),
        migrations.DeleteModel(
            name='TrCredit_in_Good',
        ),
        migrations.DeleteModel(
            name='TrCredit_in_Money',
        ),
        migrations.DeleteModel(
            name='TrCredit_out_Money',
        ),
        migrations.DeleteModel(
            name='TrDeposit_in',
        ),
        migrations.DeleteModel(
            name='TrDeposit_out',
        ),
        migrations.DeleteModel(
            name='TrDistribution',
        ),
        migrations.AddField(
            model_name='restitution',
            name='original_taking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Taking'),
        ),
        migrations.AddField(
            model_name='recovery',
            name='excepted_accounts',
            field=models.ManyToManyField(to='core.Account'),
        ),
        migrations.AddField(
            model_name='proceedssharing',
            name='excepted_accounts',
            field=models.ManyToManyField(to='core.Account'),
        ),
        migrations.AddField(
            model_name='inpayment',
            name='moneybox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MoneyBox'),
        ),
        migrations.AddField(
            model_name='donation',
            name='excepted_accounts',
            field=models.ManyToManyField(to='core.Account'),
        ),
        migrations.AddField(
            model_name='depositation',
            name='moneybox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MoneyBox'),
        ),
        migrations.AddField(
            model_name='costsharing',
            name='excepted_accounts',
            field=models.ManyToManyField(to='core.Account'),
        ),
    ]
