# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-10 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_transaction_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Transaction')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Batch')),
            ],
            bases=('core.transaction',),
        ),
        migrations.RemoveField(
            model_name='restitution',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='restitution',
            name='transaction_ptr',
        ),
        migrations.RemoveField(
            model_name='taking',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='taking',
            name='transaction_ptr',
        ),
        migrations.AlterField(
            model_name='inpayment',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='restitution',
            name='batchtransaction_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BatchTransaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taking',
            name='batchtransaction_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BatchTransaction'),
            preserve_default=False,
        ),
    ]
