# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-10 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_insertion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
