# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-10 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20170110_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchtransaction',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='batchtransaction',
            name='transaction_ptr',
        ),
        migrations.RemoveField(
            model_name='restitution',
            name='batchtransaction_ptr',
        ),
        migrations.RemoveField(
            model_name='taking',
            name='batchtransaction_ptr',
        ),
        migrations.AddField(
            model_name='restitution',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restitution',
            name='transaction_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Transaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taking',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taking',
            name='transaction_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Transaction'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BatchTransaction',
        ),
    ]
