# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20161105_0403'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PayOutbalance',
            new_name='PayOutcredit',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='balance',
            new_name='credit',
        ),
    ]
