# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-13 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20170813_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseStatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='purchasestatus',
            name='purchase_status_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PurchaseStatusType'),
        ),
    ]
