# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-14 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_purchasestatus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificpurchase',
            name='status',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='core.PurchaseStatus'),
            preserve_default=False,
        ),
    ]
