# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-16 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_specificpurchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_account', to='core.Account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='core.Account'),
        ),
    ]
