# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-21 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20170821_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='notice',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comment',
        ),
    ]
