# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-21 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20170821_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notice',
            field=models.TextField(blank=True),
        ),
    ]
