# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-22 08:21
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_user_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('rate', models.FloatField(default=1)),
                ('comment', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
            ],
        ),
        migrations.RemoveField(
            model_name='accpayphase',
            name='account',
        ),
        migrations.DeleteModel(
            name='AccPayPhase',
        ),
    ]
