# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-22 10:16
from __future__ import unicode_literals

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_membershipfee_mode'),
    ]

    operations = [
    ]
