# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-22 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20170822_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipfee',
            name='mode',
        ),
    ]
