# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-22 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20170822_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='customregularfee',
            name='membershipfeemode_ptr',
        ),
        migrations.RemoveField(
            model_name='customregularfee',
            name='period',
        ),
        migrations.AlterField(
            model_name='accountmembershipfeephase',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MembershipFee'),
        ),
        migrations.DeleteModel(
            name='CustomRegularFee',
        ),
        migrations.DeleteModel(
            name='MembershipFeeMode',
        ),
    ]
