# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-22 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20170822_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRegularFee',
            fields=[
                ('membershipfee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.MembershipFee')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TimePeriod')),
            ],
            bases=('core.membershipfee',),
        ),
        migrations.CreateModel(
            name='NativeFee',
            fields=[
                ('membershipfee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.MembershipFee')),
                ('no', models.IntegerField()),
            ],
            bases=('core.membershipfee',),
        ),
    ]
