# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-22 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_customregularfee_nativefee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmembershipfeephase',
            name='account',
        ),
        migrations.RemoveField(
            model_name='accountmembershipfeephase',
            name='last_edited_by',
        ),
        migrations.RemoveField(
            model_name='accountmembershipfeephase',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='customregularfee',
            name='membershipfee_ptr',
        ),
        migrations.RemoveField(
            model_name='customregularfee',
            name='period',
        ),
        migrations.RemoveField(
            model_name='nativefee',
            name='membershipfee_ptr',
        ),
        migrations.DeleteModel(
            name='AccountMembershipFeePhase',
        ),
        migrations.DeleteModel(
            name='CustomRegularFee',
        ),
        migrations.DeleteModel(
            name='MembershipFee',
        ),
        migrations.DeleteModel(
            name='NativeFee',
        ),
    ]
