# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-25 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_custommembershipfeephase_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='displayed_time_period_for_membership_fees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TimePeriod'),
        ),
    ]
