# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-02 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_account_displayed_time_period_for_membership_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyBoxType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='moneyboxstock',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='moneyboxstock',
            name='money_box',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='name',
        ),
        migrations.AddField(
            model_name='currency',
            name='iso_code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='currency',
            name='iso_num',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='currency',
            name='short_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='moneybox',
            name='currency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='conversion_rate',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='moneybox',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='MoneyBoxStock',
        ),
        migrations.AddField(
            model_name='moneybox',
            name='money_boy_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.MoneyBoxType'),
        ),
    ]
