# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-02 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20180502_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='long_date_format',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='short_date_format',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
