# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-02 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20180502_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='long_date_format',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='short_date_format',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
